//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECFDI.KitDesarrollo.WCFCertificar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutenticarPeticion", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class AutenticarPeticion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdProveedorUsuarioField;
        
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProveedorUsuario {
            get {
                return this.IdProveedorUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdProveedorUsuarioField, value) != true)) {
                    this.IdProveedorUsuarioField = value;
                    this.RaisePropertyChanged("IdProveedorUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WCFRespuesta", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIRespuesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIRespuesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIRespuesta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SECFDI.KitDesarrollo.WCFCertificar.AutenticarRespuesta))]
    public partial class WCFRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SECFDI.KitDesarrollo.WCFCertificar.Estatus EstatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SECFDI.KitDesarrollo.WCFCertificar.Estatus Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusField, value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estatus", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class Estatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DetieneEjecucionProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformacionTecnicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DetieneEjecucionProveedor {
            get {
                return this.DetieneEjecucionProveedorField;
            }
            set {
                if ((this.DetieneEjecucionProveedorField.Equals(value) != true)) {
                    this.DetieneEjecucionProveedorField = value;
                    this.RaisePropertyChanged("DetieneEjecucionProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformacionTecnica {
            get {
                return this.InformacionTecnicaField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacionTecnicaField, value) != true)) {
                    this.InformacionTecnicaField = value;
                    this.RaisePropertyChanged("InformacionTecnica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimbrarCFDIRespuesta", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class TimbrarCFDIRespuesta : SECFDI.KitDesarrollo.WCFCertificar.WCFRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SECFDI.KitDesarrollo.WCFCertificar.Timbre TimbradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SECFDI.KitDesarrollo.WCFCertificar.Timbre Timbrado {
            get {
                return this.TimbradoField;
            }
            set {
                if ((object.ReferenceEquals(this.TimbradoField, value) != true)) {
                    this.TimbradoField = value;
                    this.RaisePropertyChanged("Timbrado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelarCFDIRespuesta", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class CancelarCFDIRespuesta : SECFDI.KitDesarrollo.WCFCertificar.WCFRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SECFDI.KitDesarrollo.WCFCertificar.FoliosRespuesta[] FoliosRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SECFDI.KitDesarrollo.WCFCertificar.FoliosRespuesta[] FoliosRespuesta {
            get {
                return this.FoliosRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.FoliosRespuestaField, value) != true)) {
                    this.FoliosRespuestaField = value;
                    this.RaisePropertyChanged("FoliosRespuesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneraCFDIRespuesta", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class GeneraCFDIRespuesta : SECFDI.KitDesarrollo.WCFCertificar.WCFRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SECFDI.KitDesarrollo.WCFCertificar.CFDITimbrado CFDITimbradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SECFDI.KitDesarrollo.WCFCertificar.CFDITimbrado CFDITimbrado {
            get {
                return this.CFDITimbradoField;
            }
            set {
                if ((object.ReferenceEquals(this.CFDITimbradoField, value) != true)) {
                    this.CFDITimbradoField = value;
                    this.RaisePropertyChanged("CFDITimbrado");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutenticarRespuesta", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class AutenticarRespuesta : SECFDI.KitDesarrollo.WCFCertificar.WCFRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timbre", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class Timbre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdVersionTimbradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CadenaOriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelloCFDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelloSATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoCertificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcProvCertifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeyendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimbreXMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVersionTimbrado {
            get {
                return this.IdVersionTimbradoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVersionTimbradoField, value) != true)) {
                    this.IdVersionTimbradoField = value;
                    this.RaisePropertyChanged("IdVersionTimbrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string CadenaOriginal {
            get {
                return this.CadenaOriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.CadenaOriginalField, value) != true)) {
                    this.CadenaOriginalField = value;
                    this.RaisePropertyChanged("CadenaOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string SelloCFD {
            get {
                return this.SelloCFDField;
            }
            set {
                if ((object.ReferenceEquals(this.SelloCFDField, value) != true)) {
                    this.SelloCFDField = value;
                    this.RaisePropertyChanged("SelloCFD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string SelloSAT {
            get {
                return this.SelloSATField;
            }
            set {
                if ((object.ReferenceEquals(this.SelloSATField, value) != true)) {
                    this.SelloSATField = value;
                    this.RaisePropertyChanged("SelloSAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string NoCertificado {
            get {
                return this.NoCertificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoCertificadoField, value) != true)) {
                    this.NoCertificadoField = value;
                    this.RaisePropertyChanged("NoCertificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string RfcProvCertif {
            get {
                return this.RfcProvCertifField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcProvCertifField, value) != true)) {
                    this.RfcProvCertifField = value;
                    this.RaisePropertyChanged("RfcProvCertif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Leyenda {
            get {
                return this.LeyendaField;
            }
            set {
                if ((object.ReferenceEquals(this.LeyendaField, value) != true)) {
                    this.LeyendaField = value;
                    this.RaisePropertyChanged("Leyenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string TimbreXML {
            get {
                return this.TimbreXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.TimbreXMLField, value) != true)) {
                    this.TimbreXMLField = value;
                    this.RaisePropertyChanged("TimbreXML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoliosRespuesta", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class FoliosRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SECFDI.KitDesarrollo.WCFCertificar.Estatus EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SECFDI.KitDesarrollo.WCFCertificar.Estatus Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusField, value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UUIDField, value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CFDITimbrado", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class CFDITimbrado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SECFDI.KitDesarrollo.WCFCertificar.CFDITimbre RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SECFDI.KitDesarrollo.WCFCertificar.CFDITimbre Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CFDITimbre", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class CFDITimbre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<string, string> TimbreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> Timbre {
            get {
                return this.TimbreField;
            }
            set {
                if ((object.ReferenceEquals(this.TimbreField, value) != true)) {
                    this.TimbreField = value;
                    this.RaisePropertyChanged("Timbre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimbrarCFDIPeticion", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class TimbrarCFDIPeticion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string XMLEntradaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string XMLEntrada {
            get {
                return this.XMLEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLEntradaField, value) != true)) {
                    this.XMLEntradaField = value;
                    this.RaisePropertyChanged("XMLEntrada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelarCFDIPeticion", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class CancelarCFDIPeticion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RFCField;
        
        private string XMLEntradaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string XMLEntrada {
            get {
                return this.XMLEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLEntradaField, value) != true)) {
                    this.XMLEntradaField = value;
                    this.RaisePropertyChanged("XMLEntrada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneraCFDIPeticion", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class GeneraCFDIPeticion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SECFDI.KitDesarrollo.WCFCertificar.DatosGenerales DatosGeneralesField;
        
        private System.Collections.Generic.Dictionary<string, string> EncabezadoField;
        
        private System.Collections.Generic.Dictionary<string, string> DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AddendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SECFDI.KitDesarrollo.WCFCertificar.DatosGenerales DatosGenerales {
            get {
                return this.DatosGeneralesField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosGeneralesField, value) != true)) {
                    this.DatosGeneralesField = value;
                    this.RaisePropertyChanged("DatosGenerales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> Encabezado {
            get {
                return this.EncabezadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EncabezadoField, value) != true)) {
                    this.EncabezadoField = value;
                    this.RaisePropertyChanged("Encabezado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Collections.Generic.Dictionary<string, string> Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.Dictionary<string, string> Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Collections.Generic.Dictionary<string, string> Addenda {
            get {
                return this.AddendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AddendaField, value) != true)) {
                    this.AddendaField = value;
                    this.RaisePropertyChanged("Addenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosGenerales", Namespace="http://schemas.datacontract.org/2004/07/SECFDI.WCFLibCertificar")]
    [System.SerializableAttribute()]
    public partial class DatosGenerales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ConfiguracionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Configuracion {
            get {
                return this.ConfiguracionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfiguracionField, value) != true)) {
                    this.ConfiguracionField = value;
                    this.RaisePropertyChanged("Configuracion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFCertificar.ICertificar")]
    public interface ICertificar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/Autenticar", ReplyAction="http://tempuri.org/ICertificar/AutenticarResponse")]
        SECFDI.KitDesarrollo.WCFCertificar.AutenticarRespuesta Autenticar(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/Autenticar", ReplyAction="http://tempuri.org/ICertificar/AutenticarResponse")]
        System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.AutenticarRespuesta> AutenticarAsync(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/TimbradoMultiEmpresas", ReplyAction="http://tempuri.org/ICertificar/TimbradoMultiEmpresasResponse")]
        SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIRespuesta TimbradoMultiEmpresas(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIPeticion parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/TimbradoMultiEmpresas", ReplyAction="http://tempuri.org/ICertificar/TimbradoMultiEmpresasResponse")]
        System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIRespuesta> TimbradoMultiEmpresasAsync(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIPeticion parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/CancelarCFDIMultiEmpresa", ReplyAction="http://tempuri.org/ICertificar/CancelarCFDIMultiEmpresaResponse")]
        SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIRespuesta CancelarCFDIMultiEmpresa(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIPeticion parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/CancelarCFDIMultiEmpresa", ReplyAction="http://tempuri.org/ICertificar/CancelarCFDIMultiEmpresaResponse")]
        System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIRespuesta> CancelarCFDIMultiEmpresaAsync(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIPeticion parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/GeneraCFDI", ReplyAction="http://tempuri.org/ICertificar/GeneraCFDIResponse")]
        SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIRespuesta GeneraCFDI(SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIPeticion parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificar/GeneraCFDI", ReplyAction="http://tempuri.org/ICertificar/GeneraCFDIResponse")]
        System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIRespuesta> GeneraCFDIAsync(SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIPeticion parametro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICertificarChannel : SECFDI.KitDesarrollo.WCFCertificar.ICertificar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CertificarClient : System.ServiceModel.ClientBase<SECFDI.KitDesarrollo.WCFCertificar.ICertificar>, SECFDI.KitDesarrollo.WCFCertificar.ICertificar {
        
        public CertificarClient() {
        }
        
        public CertificarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SECFDI.KitDesarrollo.WCFCertificar.AutenticarRespuesta Autenticar(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametro) {
            return base.Channel.Autenticar(parametro);
        }
        
        public System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.AutenticarRespuesta> AutenticarAsync(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametro) {
            return base.Channel.AutenticarAsync(parametro);
        }
        
        public SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIRespuesta TimbradoMultiEmpresas(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIPeticion parametro) {
            return base.Channel.TimbradoMultiEmpresas(parametroSeguridad, parametro);
        }
        
        public System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIRespuesta> TimbradoMultiEmpresasAsync(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.TimbrarCFDIPeticion parametro) {
            return base.Channel.TimbradoMultiEmpresasAsync(parametroSeguridad, parametro);
        }
        
        public SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIRespuesta CancelarCFDIMultiEmpresa(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIPeticion parametro) {
            return base.Channel.CancelarCFDIMultiEmpresa(parametroSeguridad, parametro);
        }
        
        public System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIRespuesta> CancelarCFDIMultiEmpresaAsync(SECFDI.KitDesarrollo.WCFCertificar.AutenticarPeticion parametroSeguridad, SECFDI.KitDesarrollo.WCFCertificar.CancelarCFDIPeticion parametro) {
            return base.Channel.CancelarCFDIMultiEmpresaAsync(parametroSeguridad, parametro);
        }
        
        public SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIRespuesta GeneraCFDI(SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIPeticion parametro) {
            return base.Channel.GeneraCFDI(parametro);
        }
        
        public System.Threading.Tasks.Task<SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIRespuesta> GeneraCFDIAsync(SECFDI.KitDesarrollo.WCFCertificar.GeneraCFDIPeticion parametro) {
            return base.Channel.GeneraCFDIAsync(parametro);
        }
    }
}
